#! /bin/sh

#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#██╗██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#╚═╝╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝                                     
# Github: @iamb4uc

# Startup
picom &                                 # Blurr go brrrrrrrrrrrrrrrrrrr
lxpolkit &                              # Polkit Manger
sxhkd &                                 # Keyboard Shortcuts
xset r rate 300 50 &                    # Keyboard go brrrrrrrrrrrrrrrrrrrr
$HOME/.config/polybar/launch.sh         # Polybar

# bspc monitor -d      
bspc monitor -d 1 2 3 4 5 6 7 8 9 10    # Change the number of active instances

bspc config border_width           1
bspc config window_gap            10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a pulsemixer state="float"

feh --no-fehbg --bg-scale /home/silvolde/Pictures/girl.jpg
